name: thefashionai
description: "Fashion AI App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  crazy:
    path: C:\Users\saabd\StudioProjects\crazy
  csv: ^6.0.0
  animated_bottom_navigation_bar: ^1.4.0
  convex_bottom_bar: ^3.2.0
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  google_sign_in: ^6.2.2
  cloud_firestore: ^5.6.5
  shared_preferences: ^2.5.3
  image_picker: ^1.1.2
  firebase_storage: ^12.4.5
  google_generative_ai: ^0.2.0
  camera: ^0.10.0+1
  speech_to_text: ^6.3.0
  palette_generator: ^0.3.3
  http: ^1.1.0
  flutter_bloc: ^8.1.3
  cached_network_image: ^3.3.0
  flutter_linkify: ^5.0.2
  url_launcher: ^6.1.7
  dio: ^5.4.0
  path_provider: ^2.1.5
  path: ^1.8.3
  http_parser: ^4.0.2
  flutter_dotenv: ^5.1.0
  flutter_image_compress: ^2.0.4
  exif: ^3.1.4
  image: ^4.1.3
  cupertino_icons: ^1.0.8
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/bg.jpg
    - assets/bg2.jpg
    - assets/logo.jpg
    - assets/pixelcut-export.png
    - assets/img1.jpg
    - assets/img2.jpg
    - assets/img3.jpg
    - assets/logo1.webp
    - assets/logo2.jpg
    - assets/logo3.png
    - assets/logo4.jpg
    - assets/F0253203003_3.jpeg
    - assets/F0253203523_1.jpeg
    - assets/F0280203998_2_b47ce731-5ee4-45e5-97d0-4b8fab91c590.jpeg
    - assets/csv/questions.csv
    - assets/csv/clothing.csv
    - assets/images/
    - assets/All Brands/
    - assets/All Brands/Break Out Men/
    - assets/All Brands/Break Out Women/
    - assets/All Brands/Chase Value Men/
    - assets/All Brands/Chase Value Women/
    - assets/All Brands/Ideas Men/
    - assets/All Brands/Ideas Women/
    - assets/All Brands/Outfitter Men/
    - assets/All Brands/Outfitter Women/
    # Include all subdirectories recursively
    - assets/All Brands/Break Out Men/
    - assets/All Brands/Break Out Women/
    - assets/All Brands/Chase Value Men/
    - assets/All Brands/Chase Value Men/Chase Shalwar Kameez/
    - assets/All Brands/Chase Value Men/Chase Value Men Formal/
    - assets/All Brands/Chase Value Men/ChaseValue Shoes/
    - assets/All Brands/Chase Value Women/
    - assets/All Brands/Chase Value Women/ChaseValue Abayas/
    - assets/All Brands/Chase Value Women/ChaseValue Kurti/
    - assets/All Brands/Chase Value Women/ChaseValue Shalwar Kameez/
    - assets/All Brands/Ideas Men/
    - assets/All Brands/Ideas Men/Ideaas Man Peshawri/
    - assets/All Brands/Ideas Men/Ideaas Shirts/
    - assets/All Brands/Ideas Men/Ideas Hoodies And Sweat Shirt/
    - assets/All Brands/Ideas Men/Ideas Jackets/
    - assets/All Brands/Ideas Men/Ideas Polos/
    - assets/All Brands/Ideas Men/Ideas Waist Coat/
    - assets/All Brands/Ideas Women/
    - assets/All Brands/Ideas Women/Ideas 3 PIECE/
    - assets/All Brands/Ideas Women/Ideas Abaya/
    - assets/All Brands/Ideas Women/Ideas jackets/
    - assets/All Brands/Outfitter Men/
    - assets/All Brands/Outfitter Men/Outfitter  Active Wear/
    - assets/All Brands/Outfitter Men/Outfitter  Jeans/
    - assets/All Brands/Outfitter Men/Outfitter  Shoes/
    - assets/All Brands/Outfitter Men/Outfitter  T-Shirts/
    - assets/All Brands/Outfitter Men/Outfitter  Underwear/
    - assets/All Brands/Outfitter Men/Outfitter Shirts/
    - assets/All Brands/Outfitter Women/
    - assets/All Brands/Outfitter Women/Outfitter  Active Wear/
    - assets/All Brands/Outfitter Women/Outfitter  Shirts/
    - assets/All Brands/Outfitter Women/Outfitter  Shoes/
    - assets/All Brands/Outfitter Women/Outfitter Coats blazzers/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/logo.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/logo.jpg"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "assets/logo.jpg"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/logo.jpg"
